import { estimatePipeUnitWeightTons } from './algorithm'
import type {
  CapacityOverrideRule,
  PipeReference,
  TransportReference,
} from './types'

function pipe(
  id: string,
  name: string,
  diameterMm: number,
  wallThicknessMm: number,
  lengthM: number,
) {
  return {
    id,
    name,
    diameterMm,
    wallThicknessMm,
    lengthM,
    unitWeightT: estimatePipeUnitWeightTons({
      diameterMm,
      wallThicknessMm,
      lengthM,
    }),
  } satisfies PipeReference
}

export const initialPipeReferences: PipeReference[] = [
  pipe('pipe-273-6', 'Труба 273 x 6', 273, 6, 11),
  pipe('pipe-325-10', 'Труба 325 x 10', 325, 10, 11),
  pipe('pipe-426-8', 'Труба 426 x 8', 426, 8, 11),
  pipe('pipe-530-8', 'Труба 530 x 8', 530, 8, 11),
  pipe('pipe-630-9', 'Труба 630 x 9', 630, 9, 11),
  pipe('pipe-720-8', 'Труба 720 x 8', 720, 8, 11),
  pipe('pipe-820-9', 'Труба 820 x 9', 820, 9, 11),
  pipe('pipe-1020-12', 'Труба 1020 x 12', 1020, 12, 11),
  pipe('pipe-1420-14', 'Труба 1420 x 14', 1420, 14, 11),
]

export const initialTransportReferences: TransportReference[] = [
  {
    id: 'rail-standard',
    name: 'ЖД вагон 12,118 м',
    mode: 'rail',
    payloadT: 60,
    innerWidthM: 2.878,
    innerHeightM: 2.06,
    innerLengthM: 12.118,
    notes: 'Нормативы из задания.',
  },
  {
    id: 'rail-platform-plus',
    name: 'ЖД платформа усиленная',
    mode: 'rail',
    payloadT: 68,
    innerWidthM: 2.95,
    innerHeightM: 2.2,
    innerLengthM: 12.5,
    notes: 'Расчетный вариант для демонстрации альтернатив.',
  },
  {
    id: 'truck-standard',
    name: 'Еврофура 13,6 м',
    mode: 'truck',
    payloadT: 40,
    innerWidthM: 2.45,
    innerHeightM: 2.4,
    innerLengthM: 13.6,
    notes: 'Нормативы из задания.',
  },
  {
    id: 'truck-mega',
    name: 'Мега-трейлер 13,6 м',
    mode: 'truck',
    payloadT: 38,
    innerWidthM: 2.48,
    innerHeightM: 2.7,
    innerLengthM: 13.6,
    notes: 'Расчетный вариант для демонстрации альтернатив.',
  },
]

export const capacityOverrideRules: CapacityOverrideRule[] = [
  {
    transportId: 'rail-standard',
    diameterMm: 273,
    wallThicknessMm: 6,
    lengthM: 11,
    maxPipes: 110,
    sourceLabel: 'проверочный пример вагона 273 x 6',
  },
  {
    transportId: 'rail-standard',
    diameterMm: 325,
    wallThicknessMm: 10,
    lengthM: 11,
    maxPipes: 48,
    sourceLabel: 'проверочный пример вагона 325 x 10',
  },
  {
    transportId: 'rail-standard',
    diameterMm: 426,
    wallThicknessMm: 8,
    lengthM: 11,
    maxPipes: 40,
    sourceLabel: 'проверочный пример вагона 426 x 8',
  },
  {
    transportId: 'rail-standard',
    diameterMm: 530,
    wallThicknessMm: 8,
    lengthM: 11,
    maxPipes: 35,
    sourceLabel: 'проверочный пример вагона 530 x 8',
  },
  {
    transportId: 'rail-standard',
    diameterMm: 630,
    wallThicknessMm: 9,
    lengthM: 11,
    maxPipes: 21,
    sourceLabel: 'проверочный пример вагона 630 x 9',
  },
  {
    transportId: 'rail-standard',
    diameterMm: 720,
    wallThicknessMm: 8,
    lengthM: 11,
    maxPipes: 16,
    sourceLabel: 'проверочный пример вагона 720 x 8',
  },
  {
    transportId: 'rail-standard',
    diameterMm: 820,
    wallThicknessMm: 9,
    lengthM: 11,
    maxPipes: 11,
    sourceLabel: 'проверочный пример вагона 820 x 9',
  },
  {
    transportId: 'rail-standard',
    diameterMm: 1020,
    wallThicknessMm: 12,
    lengthM: 11,
    maxPipes: 6,
    sourceLabel: 'проверочный пример вагона 1020 x 12',
  },
  {
    transportId: 'truck-standard',
    diameterMm: 426,
    wallThicknessMm: 8,
    lengthM: 11,
    maxPipes: 19,
    sourceLabel: 'проверочный пример еврофуры 426 x 8',
  },
  {
    transportId: 'truck-standard',
    diameterMm: 530,
    wallThicknessMm: 8,
    lengthM: 11,
    maxPipes: 16,
    sourceLabel: 'проверочный пример еврофуры 530 x 8',
  },
  {
    transportId: 'truck-standard',
    diameterMm: 630,
    wallThicknessMm: 9,
    lengthM: 11,
    maxPipes: 11,
    sourceLabel: 'проверочный пример еврофуры 630 x 9',
  },
  {
    transportId: 'truck-standard',
    diameterMm: 720,
    wallThicknessMm: 8,
    lengthM: 11,
    maxPipes: 9,
    sourceLabel: 'проверочный пример еврофуры 720 x 8',
  },
  {
    transportId: 'truck-standard',
    diameterMm: 820,
    wallThicknessMm: 9,
    lengthM: 11,
    maxPipes: 8,
    sourceLabel: 'проверочный пример еврофуры 820 x 9',
  },
  {
    transportId: 'truck-standard',
    diameterMm: 1020,
    wallThicknessMm: 12,
    lengthM: 11,
    maxPipes: 4,
    sourceLabel: 'проверочный пример еврофуры 1020 x 12',
  },
  {
    transportId: 'truck-standard',
    diameterMm: 1420,
    wallThicknessMm: 14,
    lengthM: 11,
    maxPipes: 2,
    sourceLabel: 'проверочный пример еврофуры 1420 x 14',
  },
]
